import { describe, expect, it } from 'bun:test'
import { sql } from 'drizzle-orm/sql'
import {
  check,
  foreignKey,
  index,
  int64,
  interleaveInParent,
  primaryKey,
  sequence,
  spannerTable,
  string,
  timestamp
} from 'drizzle-spanner'
import { DiffRefusedError, diffSnapshots } from '../../src/differ.js'
import { serializeSchema } from '../../src/serializer.js'
import { type SpannerEntity } from '../../src/snapshot.js'

// bun:test has no .rejects.toSatisfy(); assert the rejection with a predicate.
async function rejectsMatching<T>(
  promise: Promise<T>,
  predicate: (error: unknown) => boolean
): Promise<void> {
  const rejection = await promise.then(
    () => {
      throw new Error('expected promise to reject, but it resolved')
    },
    (error: unknown) => error
  )
  if (!predicate(rejection)) {
    throw new Error(`rejected value did not match predicate: ${String(rejection)}`)
  }
}

function ddlOf(schemaExports: Record<string, unknown>): Array<SpannerEntity> {
  return serializeSchema(schemaExports)
}

const singers = spannerTable('singers', {
  id: string('id', { length: 36 }).primaryKey().defaultGenerateUuid(),
  name: string('name', { length: 'max' }).notNull()
})

describe('diffSnapshots: create', () => {
  it('emits CREATE TABLE with primary key, interleave, constraints and indexes', async () => {
    const albums = spannerTable(
      'albums',
      {
        id: string('id', { length: 36 }).notNull(),
        albumId: string('album_id', { length: 36 }).notNull(),
        plays: int64('plays'),
        updatedAt: timestamp('updated_at', { allowCommitTimestamp: true })
      },
      (t) => [
        primaryKey({ columns: [t.id, t.albumId.desc()] }),
        interleaveInParent(singers, { onDelete: 'cascade' }),
        index('idx_albums_plays').on(t.plays).nullFiltered().storing(t.updatedAt),
        check('positive_plays', sql`${t.plays} >= 0`)
      ]
    )
    const { statements } = await diffSnapshots([], ddlOf({ singers, albums }))
    expect(statements).toEqual([
      'CREATE TABLE `singers` (\n' +
        '  `id` STRING(36) NOT NULL DEFAULT (GENERATE_UUID()),\n' +
        '  `name` STRING(MAX) NOT NULL\n' +
        ') PRIMARY KEY (`id`)',
      'CREATE TABLE `albums` (\n' +
        '  `id` STRING(36) NOT NULL,\n' +
        '  `album_id` STRING(36) NOT NULL,\n' +
        '  `plays` INT64,\n' +
        '  `updated_at` TIMESTAMP OPTIONS (allow_commit_timestamp = true),\n' +
        '  CONSTRAINT `positive_plays` CHECK (`plays` >= 0)\n' +
        ') PRIMARY KEY (`id`, `album_id` DESC),\n' +
        '  INTERLEAVE IN PARENT `singers` ON DELETE CASCADE',
      'CREATE NULL_FILTERED INDEX `idx_albums_plays` ON `albums` (`plays`) STORING (`updated_at`)'
    ])
  })

  it('orders interleaved children after parents regardless of export order', async () => {
    const children = spannerTable(
      'children',
      {
        id: string('id', { length: 36 }).notNull(),
        childId: string('child_id', { length: 36 }).notNull()
      },
      (t) => [primaryKey({ columns: [t.id, t.childId] }), interleaveInParent(singers)]
    )
    const { statements } = await diffSnapshots([], ddlOf({ children, singers }))
    expect(statements[0]).toContain('CREATE TABLE `singers`')
    expect(statements[1]).toContain('CREATE TABLE `children`')
    expect(statements[1]).toContain(
      'INTERLEAVE IN PARENT `singers` ON DELETE NO ACTION'
    )
  })

  it('creates sequences before tables and adds foreign keys afterward', async () => {
    const seq = sequence('ids')
    const albums = spannerTable(
      'albums',
      {
        id: string('id', { length: 36 }).primaryKey(),
        singerId: string('singer_id', { length: 36 })
      },
      (t) => [
        foreignKey({ columns: [t.singerId], foreignColumns: [singers.id] }).onDelete(
          'cascade'
        )
      ]
    )
    const { statements } = await diffSnapshots([], ddlOf({ seq, singers, albums }))
    expect(statements[0]).toBe(
      "CREATE SEQUENCE `ids` OPTIONS (sequence_kind = 'bit_reversed_positive')"
    )
    expect(statements[3]).toContain(
      'ALTER TABLE `albums` ADD CONSTRAINT `fk_albums_singer_id` FOREIGN KEY (`singer_id`) REFERENCES `singers` (`id`) ON DELETE CASCADE'
    )
  })

  it('emits TOKENLIST generated columns as HIDDEN (Spanner requires it)', async () => {
    const { tokenlist } = await import('drizzle-spanner')
    const t = spannerTable('t', {
      id: string('id', { length: 36 }).primaryKey(),
      txt: string('txt', { length: 'max' }),
      tok: tokenlist('tok').generatedAlwaysAs(sql`TOKENIZE_FULLTEXT(txt)`)
    })
    const { statements } = await diffSnapshots([], ddlOf({ t }))
    expect(statements[0]).toContain(
      '`tok` TOKENLIST AS (TOKENIZE_FULLTEXT(txt)) HIDDEN'
    )
    expect(statements[0]).not.toContain('STORED')
  })

  it('emits identity columns as GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)', async () => {
    const t = spannerTable('t', {
      id: int64('id').generatedAsIdentity().primaryKey()
    })
    const { statements } = await diffSnapshots([], ddlOf({ t }))
    expect(statements[0]).toContain(
      '`id` INT64 NOT NULL GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)'
    )
  })
})

describe('diffSnapshots: column changes', () => {
  const prev = ddlOf({ singers })

  it('adds columns via ALTER TABLE ADD COLUMN', async () => {
    const next = spannerTable('singers', {
      id: string('id', { length: 36 }).primaryKey().defaultGenerateUuid(),
      name: string('name', { length: 'max' }).notNull(),
      plays: int64('plays')
    })
    const { statements } = await diffSnapshots(prev, ddlOf({ singers: next }))
    expect(statements).toEqual(['ALTER TABLE `singers` ADD COLUMN `plays` INT64'])
  })

  it('drops columns via ALTER TABLE DROP COLUMN when allowed', async () => {
    const next = spannerTable('singers', {
      id: string('id', { length: 36 }).primaryKey().defaultGenerateUuid()
    })
    const { statements } = await diffSnapshots(prev, ddlOf({ singers: next }), {
      acceptDrops: true
    })
    expect(statements).toEqual(['ALTER TABLE `singers` DROP COLUMN `name`'])
  })

  it('widens STRING lengths via ALTER COLUMN restating the type', async () => {
    const before = spannerTable('t', {
      id: string('id', { length: 36 }).primaryKey(),
      bio: string('bio', { length: 100 })
    })
    const after = spannerTable('t', {
      id: string('id', { length: 36 }).primaryKey(),
      bio: string('bio', { length: 'max' }).notNull()
    })
    const { statements } = await diffSnapshots(
      ddlOf({ t: before }),
      ddlOf({ t: after })
    )
    expect(statements).toEqual([
      'ALTER TABLE `t` ALTER COLUMN `bio` STRING(MAX) NOT NULL'
    ])
  })

  it('changes defaults via SET DEFAULT and DROP DEFAULT', async () => {
    const before = spannerTable('t', {
      id: string('id', { length: 36 }).primaryKey(),
      a: int64('a').default(1),
      b: int64('b').default(2)
    })
    const after = spannerTable('t', {
      id: string('id', { length: 36 }).primaryKey(),
      a: int64('a').default(9),
      b: int64('b')
    })
    const { statements } = await diffSnapshots(
      ddlOf({ t: before }),
      ddlOf({ t: after })
    )
    expect(statements).toEqual([
      'ALTER TABLE `t` ALTER COLUMN `a` SET DEFAULT (9)',
      'ALTER TABLE `t` ALTER COLUMN `b` DROP DEFAULT'
    ])
  })

  it('toggles allow_commit_timestamp via SET OPTIONS', async () => {
    const before = spannerTable('t', {
      id: string('id', { length: 36 }).primaryKey(),
      at: timestamp('at')
    })
    const after = spannerTable('t', {
      id: string('id', { length: 36 }).primaryKey(),
      at: timestamp('at', { allowCommitTimestamp: true })
    })
    const { statements } = await diffSnapshots(
      ddlOf({ t: before }),
      ddlOf({ t: after })
    )
    expect(statements).toEqual([
      'ALTER TABLE `t` ALTER COLUMN `at` SET OPTIONS (allow_commit_timestamp = true)'
    ])
  })
})

describe('diffSnapshots: index changes', () => {
  it('recreates a changed index and drops removed ones first', async () => {
    const before = spannerTable(
      't',
      {
        id: string('id', { length: 36 }).primaryKey(),
        a: string('a', { length: 10 }),
        b: string('b', { length: 10 })
      },
      (self) => [index('idx_a').on(self.a), index('idx_b').on(self.b)]
    )
    const after = spannerTable(
      't',
      {
        id: string('id', { length: 36 }).primaryKey(),
        a: string('a', { length: 10 }),
        b: string('b', { length: 10 })
      },
      (self) => [index('idx_a').on(self.a).nullFiltered()]
    )
    const { statements } = await diffSnapshots(
      ddlOf({ t: before }),
      ddlOf({ t: after })
    )
    expect(statements).toEqual([
      'DROP INDEX `idx_a`',
      'DROP INDEX `idx_b`',
      'CREATE NULL_FILTERED INDEX `idx_a` ON `t` (`a`)'
    ])
  })
})

describe('diffSnapshots: renames', () => {
  const before = ddlOf({ singers })

  it('resolves a table rename through the resolver and emits RENAME TABLE', async () => {
    const renamed = spannerTable('artists', {
      id: string('id', { length: 36 }).primaryKey().defaultGenerateUuid(),
      name: string('name', { length: 'max' }).notNull()
    })
    const { statements, renames } = await diffSnapshots(before, ddlOf({ renamed }), {
      resolveRename: async (candidate) =>
        candidate.kind === 'table' && candidate.dropped === 'singers' ? 'artists' : null
    })
    expect(statements).toEqual(['RENAME TABLE `singers` TO `artists`'])
    expect(renames).toEqual([{ from: 'singers', to: 'artists' }])
  })

  it('refuses a column rename with the manual path (Spanner has no RENAME COLUMN)', async () => {
    const renamed = spannerTable('singers', {
      id: string('id', { length: 36 }).primaryKey().defaultGenerateUuid(),
      fullName: string('full_name', { length: 'max' }).notNull()
    })
    await rejectsMatching(
      diffSnapshots(before, ddlOf({ singers: renamed }), {
        resolveRename: async () => 'full_name'
      }),
      (error: unknown) =>
        error instanceof DiffRefusedError &&
        error.diagnostics.some(
          (diagnostic) =>
            diagnostic.kind === 'column-rename' &&
            /new column.*backfill.*drop/is.test(diagnostic.message)
        )
    )
  })

  it('treats an unresolved candidate as drop+create when the resolver declines', async () => {
    const renamed = spannerTable('singers', {
      id: string('id', { length: 36 }).primaryKey().defaultGenerateUuid(),
      fullName: string('full_name', { length: 'max' }).notNull()
    })
    const { statements } = await diffSnapshots(before, ddlOf({ singers: renamed }), {
      resolveRename: async () => null
    })
    expect(statements).toEqual([
      'ALTER TABLE `singers` DROP COLUMN `name`',
      'ALTER TABLE `singers` ADD COLUMN `full_name` STRING(MAX) NOT NULL'
    ])
  })

  it('refuses ambiguous renames without a resolver unless drops are accepted', async () => {
    const renamed = spannerTable('singers', {
      id: string('id', { length: 36 }).primaryKey().defaultGenerateUuid(),
      fullName: string('full_name', { length: 'max' }).notNull()
    })
    await rejectsMatching(
      diffSnapshots(before, ddlOf({ singers: renamed })),
      (error: unknown) =>
        error instanceof DiffRefusedError &&
        error.diagnostics.some((diagnostic) => diagnostic.kind === 'ambiguous-rename')
    )
    const { statements } = await diffSnapshots(before, ddlOf({ singers: renamed }), {
      acceptDrops: true
    })
    expect(statements).toHaveLength(2)
  })
})

describe('diffSnapshots: refuse-and-explain', () => {
  it('refuses a primary-key change with the manual path', async () => {
    const before = spannerTable('t', { id: string('id', { length: 36 }).primaryKey() })
    const after = spannerTable(
      't',
      {
        id: string('id', { length: 36 }).notNull(),
        v: int64('v').notNull()
      },
      (self) => [primaryKey({ columns: [self.id, self.v] })]
    )
    await rejectsMatching(
      diffSnapshots(ddlOf({ t: before }), ddlOf({ t: after })),
      (error: unknown) =>
        error instanceof DiffRefusedError &&
        error.diagnostics.some(
          (diagnostic) =>
            diagnostic.kind === 'primary-key-change' &&
            diagnostic.table === 't' &&
            /new table.*backfill.*swap/is.test(diagnostic.message)
        )
    )
  })

  it('refuses an interleave change', async () => {
    const parent = spannerTable('p', { id: string('id', { length: 36 }).primaryKey() })
    const before = spannerTable(
      'c',
      {
        id: string('id', { length: 36 }).notNull(),
        cid: string('cid', { length: 36 }).notNull()
      },
      (self) => [
        primaryKey({ columns: [self.id, self.cid] }),
        interleaveInParent(parent)
      ]
    )
    const after = spannerTable(
      'c',
      {
        id: string('id', { length: 36 }).notNull(),
        cid: string('cid', { length: 36 }).notNull()
      },
      (self) => [primaryKey({ columns: [self.id, self.cid] })]
    )
    await rejectsMatching(
      diffSnapshots(ddlOf({ parent, c: before }), ddlOf({ parent, c: after })),
      (error: unknown) =>
        error instanceof DiffRefusedError &&
        error.diagnostics.some((diagnostic) => diagnostic.kind === 'interleave-change')
    )
  })

  it('refuses a type change Spanner disallows', async () => {
    const before = spannerTable('t', {
      id: string('id', { length: 36 }).primaryKey(),
      v: int64('v')
    })
    const after = spannerTable('t', {
      id: string('id', { length: 36 }).primaryKey(),
      v: string('v', { length: 'max' })
    })
    await rejectsMatching(
      diffSnapshots(ddlOf({ t: before }), ddlOf({ t: after })),
      (error: unknown) =>
        error instanceof DiffRefusedError &&
        error.diagnostics.some(
          (diagnostic) =>
            diagnostic.kind === 'column-type-change' &&
            /INT64.*STRING/s.test(diagnostic.message)
        )
    )
  })

  it('refuses a generated-column expression change', async () => {
    const before = spannerTable('t', {
      id: string('id', { length: 36 }).primaryKey(),
      g: int64('g').generatedAlwaysAs(sql`1 + 1`)
    })
    const after = spannerTable('t', {
      id: string('id', { length: 36 }).primaryKey(),
      g: int64('g').generatedAlwaysAs(sql`2 + 2`)
    })
    await rejectsMatching(
      diffSnapshots(ddlOf({ t: before }), ddlOf({ t: after })),
      (error: unknown) =>
        error instanceof DiffRefusedError &&
        error.diagnostics.some(
          (diagnostic) => diagnostic.kind === 'generated-column-change'
        )
    )
  })

  it('reports an empty diff as no statements', async () => {
    const { statements, renames } = await diffSnapshots(
      ddlOf({ singers }),
      ddlOf({ singers })
    )
    expect(statements).toEqual([])
    expect(renames).toEqual([])
  })
})

describe('diffSnapshots: drops', () => {
  it('drops indexes and interleaved children before parents', async () => {
    const parent = spannerTable('p', { id: string('id', { length: 36 }).primaryKey() })
    const child = spannerTable(
      'c',
      {
        id: string('id', { length: 36 }).notNull(),
        cid: string('cid', { length: 36 }).notNull(),
        v: int64('v')
      },
      (self) => [
        primaryKey({ columns: [self.id, self.cid] }),
        interleaveInParent(parent),
        index('idx_c_v').on(self.v)
      ]
    )
    const { statements } = await diffSnapshots(ddlOf({ parent, child }), [], {
      acceptDrops: true
    })
    expect(statements).toEqual([
      'DROP INDEX `idx_c_v`',
      'DROP TABLE `c`',
      'DROP TABLE `p`'
    ])
  })
})

describe('diffSnapshots: foreign-key dependencies', () => {
  const tables = ['a', 'b'].map((name) =>
    spannerTable(name, {
      id: int64('id').primaryKey()
    })
  )
  const base = ddlOf({ a: tables[0], b: tables[1] })
  const cycle: Array<SpannerEntity> = [
    ...base,
    {
      entityType: 'fks',
      table: 'a',
      name: 'a_b',
      columns: ['id'],
      foreignTable: 'b',
      foreignColumns: ['id'],
      onDelete: 'noAction'
    },
    {
      entityType: 'fks',
      table: 'b',
      name: 'b_a',
      columns: ['id'],
      foreignTable: 'a',
      foreignColumns: ['id'],
      onDelete: 'noAction'
    }
  ]

  it('creates mutually referencing tables before either foreign key', async () => {
    const { statements } = await diffSnapshots([], cycle)
    expect(statements).toHaveLength(4)
    expect(statements[0]).toStartWith('CREATE TABLE `a`')
    expect(statements[1]).toStartWith('CREATE TABLE `b`')
    expect(statements[0]).not.toContain('FOREIGN KEY')
    expect(statements[1]).not.toContain('FOREIGN KEY')
    expect(statements.slice(2)).toEqual([
      'ALTER TABLE `a` ADD CONSTRAINT `a_b` FOREIGN KEY (`id`) REFERENCES `b` (`id`)',
      'ALTER TABLE `b` ADD CONSTRAINT `b_a` FOREIGN KEY (`id`) REFERENCES `a` (`id`)'
    ])
  })

  it('drops both foreign keys before dropping mutually referencing tables', async () => {
    const { statements } = await diffSnapshots(cycle, [])
    expect(statements).toEqual([
      'ALTER TABLE `a` DROP CONSTRAINT `a_b`',
      'ALTER TABLE `b` DROP CONSTRAINT `b_a`',
      'DROP TABLE `b`',
      'DROP TABLE `a`'
    ])
  })

  it('removes an incoming reference from a surviving table before dropping its target', async () => {
    const surviving = base.filter((entity) =>
      entity.entityType === 'tables'
        ? entity.name === 'a'
        : 'table' in entity && entity.table === 'a'
    )
    const { statements } = await diffSnapshots(cycle, surviving)
    expect(statements).toEqual([
      'ALTER TABLE `a` DROP CONSTRAINT `a_b`',
      'ALTER TABLE `b` DROP CONSTRAINT `b_a`',
      'DROP TABLE `b`'
    ])
  })

  it('adds a new referenced column before a new table foreign key', async () => {
    const previous = ddlOf({
      target: spannerTable('target', { id: int64('id').primaryKey() })
    })
    const current: Array<SpannerEntity> = [
      ...ddlOf({
        target: spannerTable('target', {
          id: int64('id').primaryKey(),
          code: int64('code')
        }),
        source: spannerTable('source', { id: int64('id').primaryKey() })
      }),
      {
        entityType: 'fks',
        table: 'source',
        name: 'source_target',
        columns: ['id'],
        foreignTable: 'target',
        foreignColumns: ['code'],
        onDelete: 'noAction'
      }
    ]
    const { statements } = await diffSnapshots(previous, current)
    expect(statements[0]).toStartWith('CREATE TABLE `source`')
    expect(statements[1]).toBe('ALTER TABLE `target` ADD COLUMN `code` INT64')
    expect(statements[2]).toStartWith('ALTER TABLE `source` ADD CONSTRAINT')
  })
})
