import {
  type CheckEntity,
  type ColumnEntity,
  type ForeignKeyAction,
  type ForeignKeyEntity,
  type IndexEntity,
  type KeyPart,
  type PrimaryKeyEntity,
  type SequenceEntity,
  type TableEntity
} from './snapshot.js'

function escapeIdentifier(name: string): string {
  return `\`${name}\``
}

function keyPartsSql(parts: Array<KeyPart>): string {
  return parts
    .map(
      (part) => `${escapeIdentifier(part.name)}${part.order === 'desc' ? ' DESC' : ''}`
    )
    .join(', ')
}

function onDeleteSql(onDelete: ForeignKeyAction): string {
  return onDelete === 'cascade' ? 'CASCADE' : 'NO ACTION'
}

/** One `name TYPE ...` column line of CREATE TABLE / ADD COLUMN / ALTER COLUMN. */
function columnDefinitionSql(column: ColumnEntity): string {
  let definition = `${escapeIdentifier(column.name)} ${column.type}`
  if (column.notNull) {
    definition += ' NOT NULL'
  }
  if (column.generatedIdentity) {
    definition += ' GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)'
  } else if (column.generated) {
    // TOKENLIST values are unreadable; Spanner requires the column HIDDEN.
    let suffix = ''
    if (column.type === 'TOKENLIST') {
      suffix = ' HIDDEN'
    } else if (column.generated.stored) {
      suffix = ' STORED'
    }
    definition += ` AS (${column.generated.as})${suffix}`
  } else if (column.default !== null) {
    definition += ` DEFAULT (${column.default})`
  }
  if (column.allowCommitTimestamp) {
    definition += ' OPTIONS (allow_commit_timestamp = true)'
  }
  return definition
}

export function foreignKeyConstraintSql(fk: ForeignKeyEntity): string {
  const columns = fk.columns.map(escapeIdentifier).join(', ')
  const foreignColumns = fk.foreignColumns.map(escapeIdentifier).join(', ')
  let constraint = `CONSTRAINT ${escapeIdentifier(fk.name)} FOREIGN KEY (${columns}) REFERENCES ${escapeIdentifier(fk.foreignTable)} (${foreignColumns})`
  // NO ACTION is Spanner's default; stating CASCADE only keeps DDL minimal.
  if (fk.onDelete === 'cascade') {
    constraint += ' ON DELETE CASCADE'
  }
  return constraint
}

export function checkConstraintSql(check: CheckEntity): string {
  return `CONSTRAINT ${escapeIdentifier(check.name)} CHECK (${check.value})`
}

export function createTableSql(
  table: TableEntity,
  columns: Array<ColumnEntity>,
  primaryKey: PrimaryKeyEntity,
  fks: Array<ForeignKeyEntity>,
  checks: Array<CheckEntity>
): string {
  const lines = [
    ...columns.map(columnDefinitionSql),
    ...fks.map(foreignKeyConstraintSql),
    ...checks.map(checkConstraintSql)
  ]
  let statement = `CREATE TABLE ${escapeIdentifier(table.name)} (\n${lines
    .map((line) => `  ${line}`)
    .join(',\n')}\n) PRIMARY KEY (${keyPartsSql(primaryKey.columns)})`
  if (table.interleave) {
    statement += `,\n  INTERLEAVE IN PARENT ${escapeIdentifier(table.interleave.parent)} ON DELETE ${onDeleteSql(table.interleave.onDelete)}`
  }
  return statement
}

export function createIndexSql(index: IndexEntity): string {
  const unique = index.unique ? 'UNIQUE ' : ''
  const nullFiltered = index.nullFiltered ? 'NULL_FILTERED ' : ''
  let statement = `CREATE ${unique}${nullFiltered}INDEX ${escapeIdentifier(index.name)} ON ${escapeIdentifier(index.table)} (${keyPartsSql(index.columns)})`
  if (index.storing.length > 0) {
    statement += ` STORING (${index.storing.map(escapeIdentifier).join(', ')})`
  }
  return statement
}

export function createSequenceSql(sequence: SequenceEntity): string {
  return `CREATE SEQUENCE ${escapeIdentifier(sequence.name)} OPTIONS (sequence_kind = '${sequence.kind}')`
}

export function dropTableSql(name: string): string {
  return `DROP TABLE ${escapeIdentifier(name)}`
}

export function dropIndexSql(name: string): string {
  return `DROP INDEX ${escapeIdentifier(name)}`
}

export function dropSequenceSql(name: string): string {
  return `DROP SEQUENCE ${escapeIdentifier(name)}`
}

export function renameTableSql(oldName: string, newName: string): string {
  return `RENAME TABLE ${escapeIdentifier(oldName)} TO ${escapeIdentifier(newName)}`
}

export function addColumnSql(column: ColumnEntity): string {
  return `ALTER TABLE ${escapeIdentifier(column.table)} ADD COLUMN ${columnDefinitionSql(column)}`
}

export function dropColumnSql(table: string, column: string): string {
  return `ALTER TABLE ${escapeIdentifier(table)} DROP COLUMN ${escapeIdentifier(column)}`
}

/** Restates type and nullability: `ALTER COLUMN c STRING(MAX) NOT NULL`. */
export function alterColumnTypeSql(column: ColumnEntity): string {
  return `ALTER TABLE ${escapeIdentifier(column.table)} ALTER COLUMN ${escapeIdentifier(column.name)} ${column.type}${column.notNull ? ' NOT NULL' : ''}`
}

export function alterColumnDefaultSql(column: ColumnEntity): string {
  const action =
    column.default === null ? 'DROP DEFAULT' : `SET DEFAULT (${column.default})`
  return `ALTER TABLE ${escapeIdentifier(column.table)} ALTER COLUMN ${escapeIdentifier(column.name)} ${action}`
}

export function alterColumnCommitTimestampSql(column: ColumnEntity): string {
  const value = column.allowCommitTimestamp ? 'true' : 'null'
  return `ALTER TABLE ${escapeIdentifier(column.table)} ALTER COLUMN ${escapeIdentifier(column.name)} SET OPTIONS (allow_commit_timestamp = ${value})`
}

export function addConstraintSql(table: string, constraint: string): string {
  return `ALTER TABLE ${escapeIdentifier(table)} ADD ${constraint}`
}

export function dropConstraintSql(table: string, name: string): string {
  return `ALTER TABLE ${escapeIdentifier(table)} DROP CONSTRAINT ${escapeIdentifier(name)}`
}
