import { randomUUID } from 'node:crypto'
import { type ForeignKeyAction } from 'drizzle-spanner'

/** The runtime's `ON DELETE` action union, re-exported as the kit's single source. */
export type { ForeignKeyAction }

/** One `{ name, order }` key part of a primary key or index. */
export interface KeyPart {
  name: string
  order: 'asc' | 'desc'
}

export interface TableEntity {
  entityType: 'tables'
  name: string
  /** `INTERLEAVE IN PARENT parent ON DELETE ...`, or null for a root table. */
  interleave: { parent: string; onDelete: ForeignKeyAction } | null
}

export interface ColumnEntity {
  entityType: 'columns'
  table: string
  name: string
  /** Rendered Spanner type, e.g. `STRING(36)`, `ARRAY<INT64>`. */
  type: string
  notNull: boolean
  /** Rendered DDL default expression, or null. */
  default: string | null
  /** Rendered `AS (expression)` for generated columns, or null. */
  generated: { as: string; stored: boolean } | null
  /** `GENERATED BY DEFAULT AS IDENTITY (BIT_REVERSED_POSITIVE)`. */
  generatedIdentity: boolean
  /** `OPTIONS (allow_commit_timestamp = true)`. */
  allowCommitTimestamp: boolean
}

export interface PrimaryKeyEntity {
  entityType: 'pks'
  table: string
  columns: Array<KeyPart>
}

export interface IndexEntity {
  entityType: 'indexes'
  table: string
  name: string
  columns: Array<KeyPart>
  unique: boolean
  nullFiltered: boolean
  storing: Array<string>
}

export interface ForeignKeyEntity {
  entityType: 'fks'
  table: string
  name: string
  columns: Array<string>
  foreignTable: string
  foreignColumns: Array<string>
  onDelete: ForeignKeyAction
}

export interface CheckEntity {
  entityType: 'checks'
  table: string
  name: string
  /** Rendered check expression with bare column names. */
  value: string
}

export interface SequenceEntity {
  entityType: 'sequences'
  name: string
  /** The only sequence kind Spanner offers. */
  kind: 'bit_reversed_positive'
}

export type SpannerEntity =
  | TableEntity
  | ColumnEntity
  | PrimaryKeyEntity
  | IndexEntity
  | ForeignKeyEntity
  | CheckEntity
  | SequenceEntity

/**
 * drizzle-kit's v8 snapshot envelope with Spanner entities
 * (`docs/research/drizzle-kit-extensibility.md`, issue #11 decision 2).
 */
export interface SpannerSnapshot {
  version: '8'
  dialect: 'spanner'
  id: string
  prevIds: Array<string>
  ddl: Array<SpannerEntity>
  /** Recorded rename resolutions, `table.old->table.new` / `old->new`. */
  renames: Array<string>
}

export interface CreateSnapshotOptions {
  id?: string
  prevIds?: Array<string>
  renames?: Array<string>
}

export function createSnapshot(
  ddl: Array<SpannerEntity>,
  options: CreateSnapshotOptions = {}
): SpannerSnapshot {
  return {
    version: '8',
    dialect: 'spanner',
    id: options.id ?? randomUUID(),
    prevIds: options.prevIds ?? [],
    ddl,
    renames: options.renames ?? []
  }
}

const ENTITY_TYPES = new Set([
  'tables',
  'columns',
  'pks',
  'indexes',
  'fks',
  'checks',
  'sequences'
])

/** Parses and shape-checks a snapshot read from disk. */
export function parseSnapshot(raw: string, source: string): SpannerSnapshot {
  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch (error) {
    throw new Error(`drizzle-spanner-kit: ${source} is not valid JSON`, {
      cause: error
    })
  }
  const snapshot = parsed as Partial<SpannerSnapshot>
  if (snapshot.version !== '8' || snapshot.dialect !== 'spanner') {
    throw new Error(
      `drizzle-spanner-kit: ${source} is not a version-8 spanner snapshot (got version ${String(
        snapshot.version
      )}, dialect ${String(snapshot.dialect)})`
    )
  }
  if (typeof snapshot.id !== 'string' || !Array.isArray(snapshot.ddl)) {
    throw new TypeError(`drizzle-spanner-kit: ${source} is missing id or ddl`)
  }
  for (const entity of snapshot.ddl) {
    const entityType = (entity as { entityType?: unknown }).entityType
    if (typeof entityType !== 'string' || !ENTITY_TYPES.has(entityType)) {
      throw new Error(
        `drizzle-spanner-kit: ${source} contains an unknown entity type ${String(entityType)}`
      )
    }
  }
  return {
    ...snapshot,
    prevIds: snapshot.prevIds ?? [],
    renames: snapshot.renames ?? []
  } as SpannerSnapshot
}
